# Generated by Django 3.1.4 on 2020-12-27 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyStaff',
        ),
    ]
