# Generated by Django 3.1.4 on 2020-12-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0002_delete_companystaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.TextField(max_length=20),
        ),
    ]
