# Generated by Django 3.1.4 on 2020-12-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0003_auto_20201228_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='query',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
