# Generated by Django 3.1.4 on 2020-12-28 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0004_auto_20201228_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='registeredat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
