# Generated by Django 3.1.4 on 2020-12-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0008_auto_20201229_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answermodel',
            old_name='question',
            new_name='query',
        ),
    ]
