# Generated by Django 3.1.4 on 2021-01-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_app', '0010_auto_20210104_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querymodel',
            name='ellaborate',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='querymodel',
            name='query',
            field=models.CharField(max_length=200),
        ),
    ]
